FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Bingo.API/Bingo.API.csproj", "Bingo.API/"]
COPY ["Bingo.Core/Bingo.Core.csproj", "Bingo.Core/"]
COPY ["Bingo.Infrastructure/Bingo.Infrastructure.csproj", "Bingo.Infrastructure/"]
RUN dotnet restore "Bingo.API/Bingo.API.csproj"
COPY . .
RUN dotnet publish "Bingo.API/Bingo.API.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Bingo.API.dll"]